# Generated by Django 5.2.1 on 2025-05-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='username',
            field=models.CharField(default='defaultuser', max_length=150, unique=True),
        ),
    ]
