# Generated by Django 5.1.9 on 2025-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
