# Generated by Django 5.1.9 on 2025-05-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_foydalanuvchi_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
