# Generated by Django 5.1.9 on 2025-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_foydalanuvchi_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
