# Generated by Django 5.2.1 on 2025-06-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_foydalanuvchi_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
