# Generated by Django 5.2.1 on 2025-06-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_foydalanuvchi_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
